config:
  tools:
    gitlab: http://gitlab.xxx.com/
    jenkins: http://jenkins.xxx.com/
    nexus: http://nexus.xxx.com/
    harbor: http://harbor.xxx.com/
    sonarqube: http://sonarqube.xxx.com/
    grafana: http://grafana.xxx.com/

  kubernetes_manage_tools:
    rainbond_ui: http://rainbond.xxx.com/
    kubernetes_ui: https://k8sui.xxx.com/

auth:
  basic:
    admin: admin333
    weiqiang: weiqiang

aws:
  credentials:
    cost-bill-name: cost-bill
    lightsail: lightsail

databases:
  mysql:
    crud:
      address: 192.168.31.249
      user: admin
      password: admin
      dbname: infrastructure
    connmaxlifetime: 10
    maxopenconns: 100
  sqlite:
    dbfile: infra.db
    connmaxlifetime: 10
    maxopenconns: 100

telegram:
  cost_call:
    bot_token: xxx
    chat_id: xxx
    call_user: "@weiqiang333"

# 定时任务, 执行周期
job:
  # 获取账单，进行数据处理
  get_billcost: "01 50 08 * * *"
  # 账单提醒. -> telegram. 支持 off. cost_call: off
  cost_call: "01 01 09 * * *"
